- name: Clean Known Hosts entries
  hosts: localhost
  tasks:
    - name: Clear Known Hosts file
      file:
        path: ~/.ssh/known_hosts
        state: absent


- name: Setup roboshop project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend Role
      role: frontend