- name: Install Nginx
  yum:
    name: nginx
    state: present


- name: remove old directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: download and Extract package
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx
    remote_src: yes

- name: Copy extracted directory
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy of nginx roboshop.config
  copy:
    src: roboshop.config
    dest: /etc/nginx/default.d/roboshop.config


- name: start nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes











